const SCREENS = {
    INTRO: 'INTRO',
    LOGIN: 'LOGIN',
    HOME: 'HOME',
    RECOMMEND: 'RECOMMEND',
    JOBLIST: 'JOBLIST',
    SCRAP: 'SCRAP',
    MY: 'MY',
    NOTIFICATION: 'NOTIFICATION',
    MENU: 'MENU',
    SETTING: 'SETTING',
};

export default SCREENS;